name: OpenRTM C++ Formula Build

on:
  workflow_dispatch:
#  push:
#    paths:
#      - "openrtm2-py[0-9]*.rb"
#      - "build.sh"
#      - ".github/workflows/build.yaml"
#  pull_request:
#    paths:
#      - "openrtm2-py[0-9]*.rb"
#      - "build.sh"
#      - ".github/workflows/build.yaml"

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-15   # arm64 Sequoia
            artifact_name: openrtm2-arm64-sequoia
          - os: macos-26   # arm64 Tahoe (macOS 26 = Tahoe)
            artifact_name: openrtm2-arm64-tahoe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Homebrew
        run: |
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $HOME/.zprofile
          eval "$(/opt/homebrew/bin/brew shellenv)"

      - name: Install dependencies
        run: |
          brew tap openrtm/omniorb
          brew tap openrtm/openrtm2

      - name: Build project
        run: |
          bash build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            *.tar.gz
            *.sha256